FROM nodered/node-red:latest-14

RUN npm install node-red-contrib-home-assistant-websocket 
#  node-red-contrib-actionflows \
#  node-red-contrib-stoptimer \
#  node-red-contrib-time-range-switch \
#  node-red-contrib-timecheck \
#  node-red-node-timeswitch
