name: Create workflows
on: [workflow_dispatch]
#  push:
#    paths:
#      - '.github/**'
jobs:
  testi:
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: |
          env | sort
      - name: Checkout
        uses: actions/checkout@v3  
        with:
          fetch-depth: 0
      - name: Shell
        run: |
          pwd
          ls -la
          tree -a -I ".git"
          echo $(date) > .github/arse
          for image in $(find ./ -maxdepth 1 -type d -not -name ".*"); do
            IMAGE_NAME=$(printf ${image} |cut -d '/' -f 2)
            echo "Creating workflow for ${IMAGE_NAME}"
            cp ".github/templates/image-template.yml" ".github/workflows/workflow_${IMAGE_NAME}"
            sed -i "s/#IMAGE_DIRECTORY/${IMAGE_NAME}/g" ".github/workflows/workflow_${IMAGE_NAME}"
          done
          git config --global user.name "jakubowy"
          git config --global user.email "30290482+jakubowy@users.noreply.github.com"
          git add .
          git commit -m "Updated workflow"
          git push
      - name: Myaction
        uses: jakubowy/docker-images/.github/actions/build-docker-image@main
        with:
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PASS }}
          directory: ${{ env.DOCKER_DIR }}
          dockerfile: ${{ env.DOCKER_FILE }}
        if: "${{ env.DOCKER_FILE != '' }}"
