name: GitHub Actions Demo
on: [push]
#  push:
#    paths:
#      - '.github/**'
jobs:
  testi:
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: |
          env | sort
      - name: Checkout
        uses: actions/checkout@v3  
        with:
          fetch-depth: 0
      - name: Shell
        run: |
          #pwd
          #ls -la
          #tree -a -I ".git"
          #echo "Getting changed files"
          #git diff --name-only HEAD HEAD~1
          DDIR=$(git diff --name-only HEAD HEAD~1 |cut -d '/' -f 1)
          DFILE=$(find ${DDIR} -type f |grep -io "dockerfile.*")
          echo "DOCKER_DIR=${DDIR}" >> $GITHUB_ENV
          echo "DOCKER_FILE=${DFILE}" >> $GITHUB_ENV
      - name: Myaction
        uses: jakubowy/docker-images/.github/actions/build-docker-image@main
        with:
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PASS }}
          directory: ${{ env.DOCKER_DIR }}
          dockerfile: ${{ env.DOCKER_FILE }}
        if: "${{ env.DOCKER_FILE != '' }}"
