name: GitHub Actions Demo
on:
  push:
    paths:
      - '.github/**'
jobs:
  testi:
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: |
          env | sort
      - name: Checkout
        uses: actions/checkout@v3  
        with:
          fetch-depth: 0
      - name: Shell
        run: |
          pwd
          ls -la
          tree -a -I ".git"
          echo "Getting changed files"
          git diff --name-only HEAD HEAD~1
          echo $USERNA  | wc -c
          echo ${{ secrets.FUCKIT }} | wc -c
        env:
          USERNA:  ${{ secrets.FUCKIT }}
          
          
      - name: Myaction
        uses: jakubowy/docker-images/.github/actions/build-docker-image@main
        with:
          username: ${{ secrets.FUCKIT }}
          password: ${{ secrets.FUCKIT }}
        
        
  docker:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Debuk
        id: maketags
        run: |
          echo "===== $GITHUB_RUN_ID"
          echo "IMAGE_NAME=jakubowy/nodered-hassio:$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "runid: ${{ env.GITHUB_RUN_ID }}"

      - name: Docker meta
        id: meta # you'll use this in the next step
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nodered-hassio
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest

      - name: Build and push
        env:
          IMAGENAME: ${{ env.GITHUB_RUN_ID }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
#          context: .
#          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
